### ISSUE TITLE
Sometimes when shutting down dockernet just freezes

### ISSUE THREAD

**Issue by gmiotto** [mpeuster/dockernet#10]
It just happens when using with a lot of docker hosts, I can't find a common thing that drives to this episode. Sometimes it happens and sometimes it does not happen.
`*** Stopping 25 links
..

^CTraceback (most recent call last):
  File "./topology.py", line 140, in <module>
    topoCreator(sys.argv[1], sys.argv[2], sys.argv[3])
  File "./topology.py", line 129, in topoCreator
    net.stop()
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 583, in stop
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 482, in stop
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 477, in delete
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 200, in delete
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 64, in cmd
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 357, in cmd
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 344, in waitOutput
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 776, in monitor
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 220, in read`

**Comment by mpeuster** [comment]
I can confirm this problem. I am investigating it, no idea why this happens.
